"""rename table EbayCategories

Revision ID: 2c41c5576f31
Revises: 6ca9b6eb5965
Create Date: 2020-04-30 10:29:11.479444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c41c5576f31'
down_revision = '6ca9b6eb5965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.String(length=50), nullable=False),
    sa.Column('categorylevel', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('categoryparentid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoryid')
    )
    op.drop_table('EbayCategories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EbayCategories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categoryname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('categorylevel', sa.INTEGER(), nullable=False),
    sa.Column('categoryid', sa.INTEGER(), nullable=False),
    sa.Column('categoryparentid', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoryid')
    )
    op.drop_table('ebay_categories')
    # ### end Alembic commands ###
