"""change id field

Revision ID: 51a9116f2b00
Revises: fdb15d55796c
Create Date: 2020-04-19 12:05:05.234251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a9116f2b00'
down_revision = 'fdb15d55796c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_name', sa.String(length=50), nullable=False),
    sa.Column('user_query', sa.String(length=100), nullable=False),
    sa.Column('chosen_categoryid', sa.Integer(), nullable=False),
    sa.Column('filter_request', sa.Text(), nullable=False),
    sa.Column('date_of_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_searches_user_id'), 'favorite_searches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_searches_user_id'), table_name='favorite_searches')
    op.drop_table('favorite_searches')
    # ### end Alembic commands ###
