"""rename tables

Revision ID: 6ca9b6eb5965
Revises: b56d670a0461
Create Date: 2020-04-30 10:25:13.647527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca9b6eb5965'
down_revision = 'b56d670a0461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EbayCategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.String(length=50), nullable=False),
    sa.Column('categorylevel', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('categoryparentid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoryid')
    )
    op.drop_table('ebay__categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay__categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categoryname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('categorylevel', sa.INTEGER(), nullable=False),
    sa.Column('categoryid', sa.INTEGER(), nullable=False),
    sa.Column('categoryparentid', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoryid')
    )
    op.drop_table('EbayCategories')
    # ### end Alembic commands ###
