"""add column item name

Revision ID: 6e92b5522016
Revises: b8ed438bfc87
Create Date: 2020-04-24 12:12:22.749095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e92b5522016'
down_revision = 'b8ed438bfc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic_items', sa.Column('item_name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic_items', 'item_name')
    # ### end Alembic commands ###
