"""добавлены колонки в таблицу favorite searches

Revision ID: 8014af5c8fce
Revises: 51a9116f2b00
Create Date: 2020-04-21 23:36:03.167703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8014af5c8fce'
down_revision = '51a9116f2b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_searches', sa.Column('statistic_status', sa.Boolean(), nullable=True))
    op.add_column('favorite_searches', sa.Column('sttistic_start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_searches', 'sttistic_start_date')
    op.drop_column('favorite_searches', 'statistic_status')
    # ### end Alembic commands ###
