"""add column bids

Revision ID: b56d670a0461
Revises: 6e92b5522016
Create Date: 2020-04-26 16:22:47.497022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56d670a0461'
down_revision = '6e92b5522016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic_items', sa.Column('bids', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic_items', 'bids')
    # ### end Alembic commands ###
