"""users tables

Revision ID: dc4146945794
Revises: 
Create Date: 2020-04-09 10:40:37.439936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4146945794'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay__categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.String(length=50), nullable=False),
    sa.Column('categorylevel', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('categoryparentid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoryid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('session_id_status', sa.Boolean(), nullable=True),
    sa.Column('hard_expiration_time', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('token_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('ebay__categories')
    # ### end Alembic commands ###
